### ISSUE TITLE
login page is not actually taking the user ID and password as listed on the screen

### ISSUE THREAD

**Issue by customer-access** [gbcdevelopers/GBC#10]
it seems as if the user ID and password are hardcoded

![capture](https://cloud.githubusercontent.com/assets/12896666/21303868/e9e5e760-c5da-11e6-9a7f-e5261ff9460c.PNG)

**Comment by rakshitdoshi2511** [comment]
Yes this is currently hardcoded to E2000 user as we didnt have consistent data for the day. Once data becomes consistent with Trip ID for users i cn open the fields for user inputs
