### ISSUE TITLE
Load  (list)

### ISSUE THREAD

**Issue by customer-access** [gbcdevelopers/GBC#18]
There won't be a lot of entries in this screen anyway ... so reformat it ... similar to select customer screen (as a suggestion)

Also ... when i look at this screen ... i don't know what to do ... there should be some indication that i need to click an item from the list

![image](https://cloud.githubusercontent.com/assets/12896666/21305163/58bf4d0e-c5e3-11e6-899f-7b37f05c6001.png)

**Comment by rakshitdoshi2511** [comment]
Completed
